version: "3"
services:
  db:
    image: postgres:10.7
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - test-data:/var/lib/postgresql/data/

volumes:
  test-data:
